# Dependencies
markdown:             redcarpet
highlighter:          pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:            date
relative_permalinks:  true

# Setup
title:                Loose Bits
tagline:              "Thoughts on distributed systems, cloud computing, and the intersection of law and technology."
#description:          ""
url:                  http://loose-bits.com
keywords:             ['ryan roemer', 'python', 'javascript', 'node.js', 'nosql',
                       'search', 'backbone.js', 'cloud', 'cloud computing', 'law', 'patents']
baseurl:              /
paginate:             3

exclude:              ["_notes", "README.md"]

# About/contact
author:
  name:               Ryan Roemer
  url:                https://twitter.com/ryan_roemer
  email:              ryan@loose-bits.com

# Social
social:
  analytics:          UA-16721875-2
  disqus:             loose-bits
  github:             http://github.com/ryan-roemer
  twitter:            https://twitter.com/ryan_roemer
  linkedin:           http://www.linkedin.com/in/ryanroemer
  feedburner:         http://feeds.feedburner.com/LooseBits
